# Generated by Django 3.2.25 on 2024-07-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('id_age', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_age', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agencia', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('contratados', models.IntegerField()),
                ('conectados', models.IntegerField()),
                ('vacaciones', models.IntegerField()),
                ('bajas', models.IntegerField()),
                ('otros_roles', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
