# Generated by Django 3.2.25 on 2024-08-04 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='bajas',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='otros_roles',
        ),
        migrations.AddField(
            model_name='registro',
            name='bajas_medicas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registro',
            name='externas_y_autobancos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registro',
            name='nuevos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registro',
            name='promotor_offline',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registro',
            name='remplazo_plataforma_rac',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='registro',
            name='conectados',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='registro',
            name='contratados',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='registro',
            name='vacaciones',
            field=models.IntegerField(default=0),
        ),
    ]
