# Generated by Django 3.2.25 on 2024-08-15 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20240803_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='contratados_optimos',
            field=models.IntegerField(default=0),
        ),
    ]
